PWD    = $(shell pwd)

COCOTB = $(PWD)/../../cocotb

VERILOG_SOURCES = $(PWD)/../hdl/spi_master.sv
TOPLEVEL        = spi_master
MODULE          = test_spi

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
